"""enforce one api key per user

Revision ID: 2319010fcad6
Revises: 2d9d667d9917
Create Date: 2026-08-28 13:32:40.563160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2319010fcad6'
down_revision: Union[str, Sequence[str], None] = '2d9d667d9917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_user_provider'), 'api_keys', type_='unique')
    op.create_unique_constraint('unique_user_api_key', 'api_keys', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_api_key', 'api_keys', type_='unique')
    op.create_unique_constraint(op.f('unique_user_provider'), 'api_keys', ['user_id', 'provider'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
