"""add session event logging

Revision ID: 2d9d667d9917
Revises: 49cc78ae0fd6
Create Date: 2026-08-23 18:31:04.322445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9d667d9917'
down_revision: Union[str, Sequence[str], None] = '49cc78ae0fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_events_created_at'), 'session_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_events_event_type'), 'session_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_session_events_session_id'), 'session_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_events_user_id'), 'session_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_events_user_id'), table_name='session_events')
    op.drop_index(op.f('ix_session_events_session_id'), table_name='session_events')
    op.drop_index(op.f('ix_session_events_event_type'), table_name='session_events')
    op.drop_index(op.f('ix_session_events_created_at'), table_name='session_events')
    op.drop_table('session_events')
    # ### end Alembic commands ###
