"""update problem model

Revision ID: 49cc78ae0fd6
Revises: a4174e7c9d0f
Create Date: 2026-08-22 19:01:56.628248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49cc78ae0fd6'
down_revision: Union[str, Sequence[str], None] = 'a4174e7c9d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('recognition_minutes', sa.Integer(), nullable=False))
    op.alter_column('problems', 'pattern',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('problems', 'examples',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               postgresql_using='examples::json')
    op.alter_column('problems', 'constraints',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               postgresql_using='constraints::json')
    op.create_index(op.f('ix_problems_pattern'), 'problems', ['pattern'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_pattern'), table_name='problems')
    op.alter_column('problems', 'constraints',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('problems', 'examples',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('problems', 'pattern',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('problems', 'recognition_minutes')
    # ### end Alembic commands ###
