"""Initial schema

Revision ID: 880ddf15d185
Revises: 
Create Date: 2026-08-04 00:12:17.853582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '880ddf15d185'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Safe to run on both a brand-new empty database (e.g. Render) and on an
    existing database that already has the old hand-made indexes.
    """
    # 1. Fresh database: create any missing tables from the models.
    #    Tables that already exist are left untouched.
    from app.database import Base
    import app.models  # noqa: F401  (registers all tables on Base)

    Base.metadata.create_all(bind=op.get_bind())

    # 2. Old hand-made indexes: drop only if they exist.
    for name in [
        "idx_api_keys_user_id",
        "idx_approaches_session_id",
        "idx_evaluations_approach_id",
        "idx_problem_hints_problem_id",
        "idx_problems_category",
        "idx_problems_difficulty",
        "idx_problems_slug",
        "idx_sessions_problem_id",
        "idx_sessions_status",
        "idx_sessions_user_id",
        "idx_users_email",
    ]:
        op.execute(f"DROP INDEX IF EXISTS {name}")

    # 3. Old unique constraints: drop only if they exist.
    op.execute("ALTER TABLE problems DROP CONSTRAINT IF EXISTS problems_slug_key")
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_email_key")

    # 4. Column type changes.
    op.alter_column('problems', 'constraints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('problems', 'examples',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)

    # 5. New indexes: create only if missing.
    op.execute("CREATE INDEX IF NOT EXISTS ix_api_keys_id ON api_keys (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_api_keys_user_id ON api_keys (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_approaches_id ON approaches (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_approaches_session_id ON approaches (session_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_evaluations_approach_id ON evaluations (approach_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_evaluations_id ON evaluations (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_problem_hints_id ON problem_hints (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_problem_hints_problem_id ON problem_hints (problem_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_problems_category ON problems (category)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_problems_difficulty ON problems (difficulty)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_problems_slug ON problems (slug)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sessions_problem_id ON sessions (problem_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sessions_status ON sessions (status)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sessions_user_id ON sessions (user_id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_users_id ON users (id)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_problem_id'), table_name='sessions')
    op.create_index(op.f('idx_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('idx_sessions_problem_id'), 'sessions', ['problem_id'], unique=False)
    op.drop_index(op.f('ix_problems_slug'), table_name='problems')
    op.drop_index(op.f('ix_problems_difficulty'), table_name='problems')
    op.drop_index(op.f('ix_problems_category'), table_name='problems')
    op.create_unique_constraint(op.f('problems_slug_key'), 'problems', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_problems_slug'), 'problems', ['slug'], unique=False)
    op.create_index(op.f('idx_problems_difficulty'), 'problems', ['difficulty'], unique=False)
    op.create_index(op.f('idx_problems_category'), 'problems', ['category'], unique=False)
    op.alter_column('problems', 'examples',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('problems', 'constraints',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_problem_hints_problem_id'), table_name='problem_hints')
    op.drop_index(op.f('ix_problem_hints_id'), table_name='problem_hints')
    op.create_index(op.f('idx_problem_hints_problem_id'), 'problem_hints', ['problem_id'], unique=False)
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_approach_id'), table_name='evaluations')
    op.create_index(op.f('idx_evaluations_approach_id'), 'evaluations', ['approach_id'], unique=False)
    op.drop_index(op.f('ix_approaches_session_id'), table_name='approaches')
    op.drop_index(op.f('ix_approaches_id'), table_name='approaches')
    op.create_index(op.f('idx_approaches_session_id'), 'approaches', ['session_id'], unique=False)
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.create_index(op.f('idx_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###
