"""Initial schema

Revision ID: 880ddf15d185
Revises: 
Create Date: 2026-08-04 00:12:17.853582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '880ddf15d185'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_api_keys_user_id'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.drop_index(op.f('idx_approaches_session_id'), table_name='approaches')
    op.create_index(op.f('ix_approaches_id'), 'approaches', ['id'], unique=False)
    op.create_index(op.f('ix_approaches_session_id'), 'approaches', ['session_id'], unique=False)
    op.drop_index(op.f('idx_evaluations_approach_id'), table_name='evaluations')
    op.create_index(op.f('ix_evaluations_approach_id'), 'evaluations', ['approach_id'], unique=False)
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.drop_index(op.f('idx_problem_hints_problem_id'), table_name='problem_hints')
    op.create_index(op.f('ix_problem_hints_id'), 'problem_hints', ['id'], unique=False)
    op.create_index(op.f('ix_problem_hints_problem_id'), 'problem_hints', ['problem_id'], unique=False)
    op.alter_column('problems', 'constraints',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('problems', 'examples',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_problems_category'), table_name='problems')
    op.drop_index(op.f('idx_problems_difficulty'), table_name='problems')
    op.drop_index(op.f('idx_problems_slug'), table_name='problems')
    op.drop_constraint(op.f('problems_slug_key'), 'problems', type_='unique')
    op.create_index(op.f('ix_problems_category'), 'problems', ['category'], unique=False)
    op.create_index(op.f('ix_problems_difficulty'), 'problems', ['difficulty'], unique=False)
    op.create_index(op.f('ix_problems_slug'), 'problems', ['slug'], unique=True)
    op.drop_index(op.f('idx_sessions_problem_id'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_status'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='sessions')
    op.create_index(op.f('ix_sessions_problem_id'), 'sessions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_problem_id'), table_name='sessions')
    op.create_index(op.f('idx_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('idx_sessions_problem_id'), 'sessions', ['problem_id'], unique=False)
    op.drop_index(op.f('ix_problems_slug'), table_name='problems')
    op.drop_index(op.f('ix_problems_difficulty'), table_name='problems')
    op.drop_index(op.f('ix_problems_category'), table_name='problems')
    op.create_unique_constraint(op.f('problems_slug_key'), 'problems', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_problems_slug'), 'problems', ['slug'], unique=False)
    op.create_index(op.f('idx_problems_difficulty'), 'problems', ['difficulty'], unique=False)
    op.create_index(op.f('idx_problems_category'), 'problems', ['category'], unique=False)
    op.alter_column('problems', 'examples',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('problems', 'constraints',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_problem_hints_problem_id'), table_name='problem_hints')
    op.drop_index(op.f('ix_problem_hints_id'), table_name='problem_hints')
    op.create_index(op.f('idx_problem_hints_problem_id'), 'problem_hints', ['problem_id'], unique=False)
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_approach_id'), table_name='evaluations')
    op.create_index(op.f('idx_evaluations_approach_id'), 'evaluations', ['approach_id'], unique=False)
    op.drop_index(op.f('ix_approaches_session_id'), table_name='approaches')
    op.drop_index(op.f('ix_approaches_id'), table_name='approaches')
    op.create_index(op.f('idx_approaches_session_id'), 'approaches', ['session_id'], unique=False)
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.create_index(op.f('idx_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    # ### end Alembic commands ###
